name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18.7.0 # Use the version that matches your project

      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm --cached -rf .
          mv dist/* . # Adjust the source directory based on your project structure
          rm -r dist
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
